// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	ID       int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID   int64 `gorm:"column:user_id;type:bigint;not null;index:user_id,priority:1" json:"user_id"`
	FollowID int64 `gorm:"column:follow_id;type:bigint;not null;index:follow_id,priority:1" json:"follow_id"`
	Delete_  int64 `gorm:"column:delete;type:tinyint;not null" json:"delete"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
