// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID   int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;uniqueIndex:id,priority:1" json:"id"`
	Name string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Pwd  string `gorm:"column:pwd;type:varchar(255);not null" json:"pwd"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
