// Code generated by Kitex v0.4.4. DO NOT EDIT.

package commentservice

import (
	"context"
	comment "github.com/HelliWrold1/quaver/kitex_gen/comment"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PublishComment(ctx context.Context, req *comment.PubReq, callOptions ...callopt.Option) (r *comment.PubResp, err error)
	ListComment(ctx context.Context, req *comment.ListReq, callOptions ...callopt.Option) (r *comment.ListResp, err error)
	DeleteComment(ctx context.Context, req *comment.DeleteReq, callOptions ...callopt.Option) (r *comment.DeleteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) PublishComment(ctx context.Context, req *comment.PubReq, callOptions ...callopt.Option) (r *comment.PubResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishComment(ctx, req)
}

func (p *kCommentServiceClient) ListComment(ctx context.Context, req *comment.ListReq, callOptions ...callopt.Option) (r *comment.ListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListComment(ctx, req)
}

func (p *kCommentServiceClient) DeleteComment(ctx context.Context, req *comment.DeleteReq, callOptions ...callopt.Option) (r *comment.DeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}
